on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: Trigger Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List Files
        run: ls -1
      - name: Create Zip File
        run: zip python.zip lambda_function.py
      - name: List Files
        run: ls -1
      - name: Push it to Lambda
        run: aws lambda update-function-code --function-name GitHubWebhookTest --zip-file fileb://python.zip --region us-east-1
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}


        
