on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: Trigger Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List File
        run: ls -1
        
