on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: Trigger Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List Files
        run: ls -1
      - name: Create Zip File
        run: zip python.zip lambda_function.py
      - name: List Files
        run: ls -1

        
